### ISSUE TITLE
Text does not appear in Chromium

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-gui#100]
None of the labels appear in Chromium on my Mint machine. Perhaps it's missing some font? They work fine in Firefox.

**Comment by tcstewar** [comment]
weird...  Chromium's happy for me....  but I get the no-labels thing if I try it on Safari.  I'm still haven't checked to see why, but it might be the same thing.

**Comment by tcstewar** [comment]
Is this still an issue?  Did we ever find out what the problem was?

**Comment by hunse** [comment]
I think it's fixed, but I have no idea what the problem was.

**Comment by tcstewar** [comment]
Weird.  Possibly an old version thing...  something to keep an eye out for, anyway.

**Comment by hunse** [comment]
I can't even find a commit that reproduces this. I have no idea where I was when I saw it. Perhaps we should start recording commit hashes along with our bug reports.

**Comment by tcstewar** [comment]
> Perhaps we should start recording commit hashes along with our bug reports.

Possibly, although in this case I don't think that would have helped, as my guess is that it had to do with having an old version of Chromium.  Or something like that.

**Comment by hunse** [comment]
You're probably right. Did this go away on Safari, too?

**Comment by tcstewar** [comment]
> Did this go away on Safari, too?

Nope; as far as I know Safari is still broken.
