### ISSUE TITLE
Modifying settings for GUI embedded in Jupyter

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-gui#1005]
I was just working on creating an MNIST example notebook for NengoFPGA that uses the embedded GUI to display the classifications. Looking at the [code](https://github.com/nengo/nengo-gui/blob/master/nengo_gui/jupyter.py#L36) there is no obvious/clean way to set the backend to use `nengo_fpga`.

@tcstewar offered this workaround:

```
viz = nengo_gui.jupyter.InlineGUI(model)  # create embedded gui object
viz.server.server.page_settings.backend = 'nengo_fpga'  # update settings
viz  # launch embedded gui
```

Adding the backend argument to the `InlineGUI` constructor would be relatively straightforward, however perhaps we would like to consider a scheme that manages all of the embedded GUI settings in some way.

**Comment by jgosmann** [comment]
You should be able to select the backend via the configure dialog too (not sure how permanent this solution is).



> manages all of the embedded GUI settings in some way

Currently the settings that in theory can be set programmatically are split into the [server settings](https://github.com/nengo/nengo-gui/blob/master/nengo_gui/guibackend.py#L388) and [page settings](https://github.com/nengo/nengo-gui/blob/master/nengo_gui/page.py#L19). I think the server settings should not be user settable in Jupyter as these are things that are managed internally by InlineGUI to make everything working. In the page settings, the config file can already be set, the editor class should not be set by the user, which only leaves the backend. So a general solution might not be necessary or over-engineering at the moment.

**Comment by bmorcos** [comment]
So perhaps it makes sense to just do a small change and add the backend to the `InlineGUI` constructor? I think it's worth adding instead of just editing the settings after creation like suggested above.
