### ISSUE TITLE
Setting slider range makes slider button inaccessible 

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#109]
Setting range to a range that does not include the slider button value in it causes the button to become lost (either off the top or bottom of the slider).

Example:
range is [-100,100] , slider is positioned at 42, set range to [-10,10], slider is now lost

As a solution I am considering setting Slider value to a max/min value of the new range as appropriate.

**Comment by tcstewar** [comment]
Good idea!  And I like the solution of using the min/max.

**Comment by tcstewar** [comment]
Fixed at some point (I think it's in #121)
