### ISSUE TITLE
Decide on text behviour when components/netgraph are shrunk

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#113]

**Comment by tcstewar** [comment]
My ideal, I think, is that the text gradually disappears and the graph takes up a larger and larger proportion of the space (i.e. the margins shrink) until the graph itself takes up all the area of the display.

**Comment by tbekolay** [comment]
@celiasmith will add in an option to the options menu to toggle this behavior, to see if it's desired.

**Comment by tbekolay** [comment]
This was done in #282. We'll ask people for their opinions once they try the options out!
