### ISSUE TITLE
Firefox arrow keys fail when editing slider values in-place

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#116]
If you click on a slider value to edit it, and then press the left or right arrow to start moving the cursor, the first keypress works fine in Firefox, but then later arrow key presses do nothing.  These key presses work fine in Chrome.

**Comment by jgosmann** [comment]
Can't reproduce. Neither with current `master` nor with `all_is_relative`.

**Comment by tcstewar** [comment]
What version of Firefox?  I'm still seeing that error in Firefox 36.0.4.

**Comment by jgosmann** [comment]
Firefox 38.0.1 on OS X.

**Comment by tcstewar** [comment]
Works for me now...  closing...  :)
