### ISSUE TITLE
Clicking to move the cursor when editing a slider value in place doesn't work

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#117]
this is likely because the click or tap event is caught by the slider and it makes the value editable again.  If the value is already editable, then it should ignore the tap event (I think).

**Comment by cchan987** [comment]
Note:
When disabling the event handler that launches the input field, the event handler that launches the pop-up menu takes over.

**Comment by jgosmann** [comment]
This seems to work with PR #169. Though, the cursor should be changed.

**Comment by tcstewar** [comment]
Doesn't work for me (Firefox 36.0.4).  But it does work in Chromium for me.

**Comment by tcstewar** [comment]
Now it works for me on Firefox 36.0.4.  Not sure what changed.  Closing!
