### ISSUE TITLE
Dragging sliders need max/min bounds

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo-gui#12]
When dragging past the bounds of a slider, the cursor position and slider get out of synch.

**Comment by cchan987** [comment]
fixed by #26

**Comment by cchan987** [comment]
when slider is dragged up/down past the boundary, slider out of synch when user attempts to drag it again.

replication steps:
-click and drag slider past down and continue down even after slider does not move down any more
-release slider
-move mouse back up and click on slider again, attempt to drag slider up. (slider does not move immediately)

**Comment by cchan987** [comment]
possible fix: 
upon slider release, if slider (drag-y value) is outside boundary, set drag-y to boundary value.
