### ISSUE TITLE
Area for resize can get screwed up

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-gui#146]
I'm not sure how this occurred, but somehow it can happen that the clicking and dragging anywhere (except close to the label) on a graph element resizes it instead of dragging it around.

Might have been caused by changing screen resolutions, resizing the browser window, or moving the window from a retina display to a non retina display.

**Comment by jgosmann** [comment]
Might be mostly a Firefox issue.

**Comment by tcstewar** [comment]
It's tricky to debug this sort of thing..  :(  Part of me hopes that it has been magically fixed somehow (maybe even by a firefox update -- that happened for us with Safari, after all).  And the ongoing refactoring might address this as well.  But in any case, we should probably take a look at this again after the refactoring and try to replicate it.

**Comment by krisfrenette** [comment]
Messed with sizing, minimizing, dragging over etc and all seems to work as expected.

**Comment by jgosmann** [comment]
Looking back at my initial comment and some recent experiences, it seems likely to me that this problem was caused by something related to retina/high DPI displays. On those displays lengths on web page can become fractional (i.e. non-integer) numbers which could screw up checks for exact equality (i.e. assuming integer numbers).

Anyways, I don't remember experiencing this problem lately, so I'm fine with closing the issue. There are definitely more pressing problems in the GUI.
