### ISSUE TITLE
Use of .length in Datastore - viz.js

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#15]
We can improve efficiency a good deal by adding a counter for the length of the data and time array to the data store object.

Increment the variable for every addition in constant time and remove the need for linear time .length calls.

**Comment by jgosmann** [comment]
Shouldn't `.length` be constant time? (At least in a sane array implementation and I'm not sure how sane JavaScript is.)

**Comment by cchan987** [comment]
I was guessing that it iterated through the array, but from some tests it does appear to be constant.
