### ISSUE TITLE
Timer slider and input sliders, jump to click location

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#17]
When clicking on a slider bar at a location where the slider is not currently located, the slider should jump to the click location.

For example: An up/down slider is currently positioned at the very top, user clicks on the middle of the slider bar, the slider jumps to the middle position.

Consideration: How to drag the entire slider object to different positions on the screen if clicks on it move the slider value.

**Comment by tcstewar** [comment]
We can currently control slider values by dragging the handle or by clicking on the handle and typing a number.  We briefly discussed this at the dev meeting today and the feeling was that the worry about repositioning the slider object noted above and the fact that no one's commented on this issue in a long while means that we should probable stick with what we have.  

If someone finds that they really would like the ability to click anywhere on the slider and have it jump there, and has a good suggestion about how to deal with the repositioning issue, please take a stab at this in a PR.  But for now I'm closing the issue.
