### ISSUE TITLE
Unnecessary for loop

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#22]
nengo_viz/static/viz_slider.js 
line 22

(arg.n_sliders) seems to be always set to 1 resulting in the loop running once every time. Is there a case where args.n_sliders will be > 1, can this for loop be removed?

**Comment by tcstewar** [comment]
Yes, ```n_sliders``` can be > 1.  Here's a case for it:

```python
model = nengo.Network()
with model:
    stimulus = nengo.Node(lambda t: (np.sin(t), np.cos(t)))
    ens = nengo.Ensemble(n_neurons=1000, dimensions=2)
    nengo.Connection(stimulus, ens)

import nengo_viz
viz = nengo_viz.Viz(model)
viz.slider(stimulus)
viz.value(ens)
viz.start()
```

I've added this example now as ```examples/2d.py```  :)
