### ISSUE TITLE
Ability to pan while zoomed into a subnetwork

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo-gui#285]
Currently if you zoom into a subnetwork in such a way that it fills up your whole screen, there is no way to pan to look around in that subnetwork. If you click and drag, you are actually moving the subnetwork around rather than moving your view. This could potentially mess up the network arrangement when you really just want to pan.

One option could be to allow the arrow keys to be used to pan, as well as clicking and dragging on the mini-map.

**Comment by studywolf** [comment]
ooh or holding alt and click-hold to drag the background, i think that's a standard thing...

**Comment by celiasmith** [comment]
do we want to worry about a touch screen solution?

Travis DeWolf wrote:

**Comment by bjkomer** [comment]
Hmm, it does get more complicated when you throw touchscreens into the mix.

One option could be to have a 'draggable' section of the component. This could be a corner, or an area at the top (similar to how you can drag browser windows around by clicking the top, but can't drag them around clicking anywhere else). When the network is collapsed, the whole thing becomes draggable, but when it is expanded this draggable region needs to be somewhere else (like the top). I have a feeling that this could get confusing to some users..
Another option could be to have some other touch combination allow it to pan all the time. Something like putting one finger stationary on the screen, and then dragging with the other.

As for on a desktop, I like the alt-click idea. If you alt-click on a browser window right now, you can drag the window around (didn't learn that until just now!), so this would override that for people. I have a feeling not many people would miss it though.

**Comment by tcstewar** [comment]
> do we want to worry about a touch screen solution?

At the moment, touch screen are horribly broken anyway, so I wouldn't worry.

**Comment by jgosmann** [comment]
On touch devices you could still use the minimap.

**Comment by krisfrenette** [comment]
This was fixed as part of #881.
