### ISSUE TITLE
Add a Taskbar to keep track of plots and sliders

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#29]
ability to minimize sliders and plots and restore them from a taskbar

**Comment by tcstewar** [comment]
I'd lean towards doing this with adding/removing plots, rather than a taskbar.  This is what we used before: you can delete a graph, and you have a method for creating a graph.  That way we don't need a cluttering task bar.

**Comment by cchan987** [comment]
We no longer need this as we have a netgraph.
