### ISSUE TITLE
Ensembles seem to resize twice as fast as nodes/networks

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#295]
When dragging at the edge of an ensemble I find that they expand/contract much quicker. I believe this is due to the ensemble being fixed in the centre during resize. Therefore pulling the side expands both sides. This causes me to have expanded it much larger than expected as I would expect it to resize like a node.

**Comment by jgosmann** [comment]
I think, that is the correct behavior. Otherwise the dragged edge would not stay where the cursor is.

**Comment by krisfrenette** [comment]
If we are going to anchor the ensemble to the middle for resizing, then this is the correct behaviour. Given the age of this issue, I am going to close this out as it is working as expected.
