### ISSUE TITLE
When window is resized smaller vertically, sim control disappears and not able to scroll down to control

### ISSUE THREAD

**Issue by amaziying** [nengo/nengo-gui#30]
Suggested fix: Make sim control stick to bottom of window viewport

Also, relevant issue: on firefox, sim control sticks to top of window viewport.

**Comment by tcstewar** [comment]
Hmm, could you add more to this error?  It looks like it's working fine for me -- I resize the window and the sim control stays stuck to the bottom of the viewport window.

**Comment by cchan987** [comment]
I believe this is a Firefox issue related to the viz_transform function using chrome specific transforms.

opened #47

**Comment by tcstewar** [comment]
Is this still happening for anyone?

**Comment by tcstewar** [comment]
Doesn't look like this still happens.  Closing!  :)
