### ISSUE TITLE
zeroing out slider with a button in the middle of the guideline

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#32]
Potential concern:
What if the slider is covering the button due to slider being near the middle,  and the user wants to zero out.

**Comment by tcstewar** [comment]
Hmm...  not sure about this, but it could be that I can't picture what it would look like.

One other possibility:  how about we just do a snap-to-zero?  So if you're within some range (maybe 0.5em) of zero, it'll go to exactly zero.

**Comment by cchan987** [comment]
Made a branch (zero_out) for this with a demo of how this would look. 
I am also not too sure we want to have this but it was suggested in the meeting and I thought I would see how it looks.

**Comment by cchan987** [comment]
In terms of snap-to-zero when within a range, how would we handle the case that the user would like to input near zero values such as 0.01?

**Comment by tcstewar** [comment]
> In terms of snap-to-zero when within a range, how would we handle the case that the user would like to input near zero values such as 0.01?

Sliders really aren't meant for that sort of exact fine control.  In the java visualizer, this was handled by right-clicking on the slider, clicking "set value", and typing in the number you want.
