### ISSUE TITLE
Don't always print code editor errors to the console

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo-gui#328]
Currently whenever code in the editor is changed, if there is a syntax error it will be printed to the console. When you are typing things into the editor, your terminal can get flooded with tons of syntax errors for every letter that you type until you finish. It would be nice if the errors only showed up in the terminal when you hit run, or possibly not at all since they are shown in the browser with a red X.

Another thing to add could be some other indication that the code has errors, such as a red box/shading around the play button. On small scripts you can see the red X on the line with the error, but if the script is longer and you have to scroll to find the X, you might not notice it. Since the simulation will still play if there is an error (I'm assuming its with the last working version of the script) the user might think they are running a model with their changes, but they are actually running an older model and do not realize it.

**Comment by krisfrenette** [comment]
This looks to have been fixed in the latest build.
