### ISSUE TITLE
"File Open" popup stuck at "built-in examples"

### ISSUE THREAD

**Issue by rfernand2** [nengo/nengo-gui#366]
When I click on the "File Open" icon, a "file explorer" type popup appears.  On my machine, this is currently set to the anaconda folder "built-in examples" and there appears to be no way to navigate to its parent directory or to another drive, so I am unable to open the file I have created in c:\nengo\rotation.py". 

The workaround for this is to start Nengo as follows:  Nengo_gui.exe c:\nengo\rotation.py

**Comment by krisfrenette** [comment]
This is no longer an issue
