### ISSUE TITLE
Occasional mysterious border outline on slider guideline

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#41]
![screenshot](https://cloud.githubusercontent.com/assets/10402911/6062877/1923984e-ad21-11e4-8c5b-c06ec8fce47a.png)

see the top and top left of the guideline for this mystery border outline.
There should be no outline, (blends perfectly with background)
cannot reliably replicate this glitch.
Unsure if it may be simply a browser issue.

**Comment by tbekolay** [comment]
This could be something to do with the element's state? Does this only happen when you click on the element, or click in a certain part? It may be gaining a psuedoclass like `:focus`, or `:active`. Modifying the CSS for those psuedoclasses could fix this.

**Comment by cchan987** [comment]
Have been doing some experimenting and it appears to have something to do with the width of the encasing graph div. When resizing to an odd width, this glitch shows up, on an even width everything is A-okay
