### ISSUE TITLE
When resizing the height of the slider component, resize slider ?

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#42]
When the height of the slider component is changed, do we want the slider to be resized as well?

my thoughts

For:
-Seems odd to have the slider being the same size as the range it traverses

Against:
-The size of the slider seems ideal for touch. Resizing to smaller sizes may prove difficult for touch users.
-Forces consistent sizes across sliders

**Comment by tcstewar** [comment]
Hmm, how it is right now the width changes but the height does not.  Are you proposing that neither should change or that both should change?
