### ISSUE TITLE
can't run sudo nengo_gui because google chrome (ubuntu)

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo-gui#420]
when you try to run `sudo nengo_gui` you get the following error on Ubuntu

``` bash
Starting nengo_gui server at http://localhost:8080
grep: write error
[1:1:0615/142947:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (0 bytes)
```

and the browser doesn't pop up. You can direct a browser to localhost and things will work, but it looks like this is from chromium not wanting to run as a super user. Being able to select browsers was brought up in issue #203, it would be nice to also be able to not call a browser at all.

**Comment by jgosmann** [comment]
Why are people trying to run nengo_gui with sudo? This seems unnecessary and potentially harmful.

**Comment by tbekolay** [comment]
In Travis's case, he needs to interact with some hardware that he can only access with `sudo`. Robots, am I right?

**Comment by studywolf** [comment]
you are correct!

haha 'people'. It's me; I am trying to run nengo_gui with sudo.

**Comment by tbekolay** [comment]
To be fair it's defs not just you! Problem is that when `python` or `pip` fail with a permissions error, the obvious fix is to just do it with `sudo`, and it'll work. `pip` should give a better error or just prompt the user to install to the home directory instead, that'd fix a lot of these types of issues...

**Comment by tbekolay** [comment]
In case anyone's curious, it's on the docket for `pip`: https://github.com/pypa/pip/issues/1668

**Comment by krisfrenette** [comment]
So far as I can tell, this is no longer an issue. I am going to close this out. Please re-open if incorrect
