### ISSUE TITLE
Shortcut for jumping to an organized view of all the components

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#43]
Potential:
-tile all components according to type (slider,plot)

**Comment by Seanny123** [comment]
Also, a shortcut for deleting them all would be nice too.

**Comment by tcstewar** [comment]
When this was brought up at the dev meeting, people seemed to agree that it's hard to come up with a generically useful algorithm for this.  So I think we'll close it for now, and if someone has a strong suggestion of exactly how this tiling should work (and how it interacts with the netgraph), that can be done as a new Issue.
