### ISSUE TITLE
Don't automatically stop simulation when code changed

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-gui#442]
It would be nice if there was a way to configure the gui to keep running even if you change the code. Perhaps highlight the play box to indicate that the model is out of date.

I've needed this while developing larger models that are expensive to build, and so I want to interact with it while coding.

My current workaround is to use an external editor.

**Comment by krisfrenette** [comment]
This looks to be fixed with the ability to prevent automatically syncing.
