### ISSUE TITLE
One some Macs (OS X 10.9.5) using trackpad right-click menu disappears

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#474]
When using Ctrl-click to do a right-click, the menu appears, but then immediately disappears when you try to move to select something.  The problem goes away when using a mouse.

**Comment by cchan987** [comment]
Could this be potentially related to #338

**Comment by jgosmann** [comment]
Works on my Mac (10.10.4).
#338 is not a Mac issue (happens also on Linux)

**Comment by krisfrenette** [comment]
This is a duplicate of #338
