### ISSUE TITLE
Include Closure Compiler into workflow

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-gui#531]
We have a really big JavaScript project and we don't have any automated syntax checking. I recommend we use the [Google Closure compiler](https://developers.google.com/closure/compiler/?hl=en) to accomplish this. Additionally, this will allow us to investigate whether compiling our JavaScript increases our load/run times.

**Comment by krisfrenette** [comment]
I agree that we should be using something, but I believe that webpack is the correct direction for this. This the direction being taken in the rewrite. I am going to close this out in favour of using something like webpack, typescript etc..
