### ISSUE TITLE
Compare DataStore and GrowableDataStore

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-gui#556]
DataStore and GrowableDataStore (contained in the SPA similarity graph pull request) have a lot of shared and duplicated code. To resolve this, I was thinking that I should either:
- Make a super-class for both of them to inherit from
- If the performance differences between both of them are negligible, just remove DataStore and keep GrowableDataStore

**Comment by krisfrenette** [comment]
This seems to be complete, so closing this out.

**Comment by jgosmann** [comment]
I disagree, there is still a lot of code duplication across DataStore and GrowableDataStore. Though, it might not be worth to refactor depending on the plans of how to proceed with the GUI.
