### ISSUE TITLE
Legend for plots

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#58]

**Comment by Seanny123** [comment]
Like for all plots by default? Or added optionally via context menu and saved in the config?

**Comment by tcstewar** [comment]
> Like for all plots by default? Or added optionally via context menu and saved in the config? I ask, because I'm probably going to have to make a legends object for the spa similarity plots.

I'm not sure.  I think it depends a lot on the UI for the legend.

One option is a legend that only appears on mouseover.  So it might just appear to the right of the graph when you do the mouseover, and then there'd be no worry about saving anything.

Another option is a permanent legend that you can toggle with the right-click menu.  That would need to have that config option saved.

**Comment by Seanny123** [comment]
My vote is for the toggle with right-click menu. That way you can set if
you want it to be slidey or not. I then imagine you could configure the
labels with a wizard-like thing. At that point though, I can't decide if
there should be a bunch of text entries for each label or if the user
should just enter a comma separated list.

**Comment by tcstewar** [comment]
> I then imagine you could configure the
> labels with a wizard-like thing. At that point though, I can't decide if
> there should be a bunch of text entries for each label or if the user
> should just enter a comma separated list.

Hmm, not sure, but that sounds like a separate thing to worry about after this PR.  No sense making this one be huger than it has to be.

> My vote is for the toggle with right-click menu.

I'd go with whatever is easiest to implement for the first version.  :)

Note that you can also go with a slightly dynamic legend that just shows the names of the top N keys...  that's sort of what we had in Nengo 1.4.... after all, we only ever really care about the top few....

**Comment by Seanny123** [comment]
@s72sue this will be relevant to the `spa_similarity.js` legend for tomorrow.

**Comment by s72sue** [comment]
Okay I will look into it and see whats the easiest approach.

**Comment by Seanny123** [comment]
My approach for this is appending an "unselectable" div to the graph object much like the label and then decorating it all with D3.js. 

Additionally, (since I like brainstorming on these threads) as I think was mentioned in #400 I would also like to investigate hovering over or clicking a data line to get it's label if it exists.

**Comment by Seanny123** [comment]
A working static legend for the `spa_similarity.js` can be found #528

**Comment by Seanny123** [comment]
Resolved a long time ago with creation of legends for Value and the Similarity plots
