### ISSUE TITLE
Fix the context menu ordering

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-gui#582]
The hide/show toggling stuff should probably be put together.

**Comment by tcstewar** [comment]
> The hide/show toggling stuff should probably be put together.

Possibly, although I'd also say that it's important to have a consistent ordering across the various different context menus.

**Comment by krisfrenette** [comment]
At this point this seems to be pretty consistent from what I can see. I am going to close this out, but if there are inconsistencies that I may have missed, please add the specifics to this issue and reopen.
