### ISSUE TITLE
Save layout

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#6]
To save the layout, we'll do the same Python code trick as nengo_gui.  We can take the current settings and generate the source code that would do that.  So instead of

``` python
viz = nengo_viz.Viz(model)
viz.slider(stimulus_A)
viz.value(ens)
viz.start()
```

it would change its own source code to

``` python
viz = nengo_viz.Viz(model)
viz.slider(stimulus_A, x=30, y=19, width=300, height=400)
viz.value(ens, x=111, y=99, width=10, height=99)
viz.start()
```

Yes, this'll be kinda tricky, and I'm not sold on the syntax yet (I might like something close to the nengo.Config system).  But that's the idea.

**Comment by cchan987** [comment]
We will also want to implement an autosave system that will trigger upon changes of elements or on regular intervals
