### ISSUE TITLE
Setting value of Semantic Pointer Cloud while network is building fails

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-gui#612]
No matter what you enter, the Semantic Pointer is seen as invalid due to an error in the JavaScript code.

**Comment by krisfrenette** [comment]
Any chance we can get an example of this happening, and possibly the JS error that is being thrown?

**Comment by jgosmann** [comment]
Tried to reproduce this, but wasn't able to.

**Comment by krisfrenette** [comment]
@jgosmann thanks. If you don't mind, since I am learning as I go, can you post the example you used so that I can see what wasn't working.

**Comment by jgosmann** [comment]
```python
import nengo
import nengo_spa as spa

vocab = spa.Vocabulary(32)
vocab.populate('A; B; C')

model = spa.Network()
with model:
    a = spa.State(vocab)
    ens = nengo.Ensemble(60000, 512)  # Adjust these number so that the build takes long enough to be able to set the value of the Semantic Pointer cloud during the build.
```

> so that I can see what wasn't working.

Not sure what you mean ... because everything was working (i.e. I could not reproduce the issue)
