### ISSUE TITLE
Scroll zooming and dragging window

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#62]
I have been looking around for some libraries we can use for this and I came across zynga/Scroller

It is under MIT License and looks pretty good. http://zynga.github.io/scroller/

What does everyone think of this library? Did anyone have alternate ideas for this?

**Comment by tcstewar** [comment]
Hmm...  at first glance it looks like overkill to me.  I was expecting to just use the interact.js that we're already using.  What sort of advantages are you thinking of for going this way?
