### ISSUE TITLE
Console autohide-toggle

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo-gui#626]
So I may have missed this option somewhere, but I would like to be able to have the console pop-up thing permanently on display. When I'm adding code and things become valid and invalid that thing is popping up and down and if i'm adding code to the end of the script the code i'm typing in gets hidden and then viewable and it's kind of a blair-witch scenario. 

So it would be nice to be like "OK i'm going to be doing some code editing for a while and let's just make that console box stay visible (even with no error) so I don't have a seizure."

**Comment by tcstewar** [comment]
+1

Or even just having it pause a few seconds before changing states would be nice.  That way it doesn't flicker in and out of existence all the time....
