### ISSUE TITLE
Decide on target browser(s) and format all code accordingly

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#63]
change VIZ.set_transform to be compatible with all browsers

**Comment by tcstewar** [comment]
For reference, I think  this is the current implementation of this function

https://github.com/nengo/nengo_gui/blob/8f492e8ec164b16d95d0084658303fbc39aae68f/nengo_gui/static/nengo.js#L26

```js
Nengo.set_transform = function(element, x, y) {
    element.style.webkitTransform =
        element.style.transform = 'translate(' + x + 'px, ' + y + 'px)';
};
```

I believe this is currently the correct cross-platform way to do it, and it doesn't seem too overly complex to me.  But we should check one are the platforms that still require the ```webkitTransform``` part.

**Comment by tcstewar** [comment]
After the dev meeting discussion, I think we're okay on this for now, and it'll also be simplified in the ongoing refactoring.  Also, that refactoring will eventually force us to be explicit about exactly what browsers we are allowing.
