### ISSUE TITLE
Code Editor Cursor Displacement

### ISSUE THREAD

**Issue by MichaelOVertolli** [nengo/nengo-gui#638]
In the chrome browser (Version 47.0.2526.106 m), running the latest release of the development environment for nengo and nengo_gui, I got a strange glitch where the cursor was displaced ~16 characters to the right. This means that when I click somewhere and hit delete, a character ~16 spaces to the left is deleted (it's hard to tell exactly how many characters as the position for the cursor is lining up for the wrong character). For example, if the sentence was:

1234567890ABCDEFG

and my cursor was  between the F and the G, it would delete the 1 (approx).

I've added two pictures of the problem before and after a highlight delete. I made it so that the highlight takes the delete to the start of the highlight (or the highlight is approx. as long as the displacement). Notice that the highlight spacing is slightly off, too (part of the zero is captured on the left).
![nengo_glitch_before](https://cloud.githubusercontent.com/assets/3731012/12420790/a6913952-be8c-11e5-854e-a5478cc1058f.png)
![nengo_glitch_after](https://cloud.githubusercontent.com/assets/3731012/12420798/ae004bd8-be8c-11e5-8114-d1e2bca1c945.png)

**Comment by tcstewar** [comment]
Fascinating...  no idea what's causing that.  One thing that's jumping out at me is that the font in your editor is not what I'd expect.  It's supposed to be some fixed-width console font.  I can't think of what could cause that to not work....   It's just standard css with "font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;" and even if you don't have those other fonts, it should fall back onto "monospace" which should do it fine.

What operating system are you running on?

**Comment by MichaelOVertolli** [comment]
Windows 8.1 Pro.

Chrome actually allows you to control the fonts for each type. It was weirdly glitching for my fixed-width type. It's now defaulting to Arial, but I still have the same cursor displacement problem.

As a further clarification, it doesn't matter whether I delete something or type something. The displacement occurs in both cases.

**Comment by tcstewar** [comment]
Hmm, I wonder if the underlying problem is that "weirdly glitching for my fixed-width type" problem.

Could you add some screenshots of that weirdly glitching aspect, before you told it to default to Arial?

**Comment by MichaelOVertolli** [comment]
No screen shots as I can't reproduce it. But here's a quick description.

In chrome, there's a "web content" section in advanced settings where you can pick your fonts. My fixed width font had Ariel selected in the drop-down, but it was showing a serif font. I had to click on another font type and then go back to Ariel to get it to read properly.

Thoughts?

**Comment by tcstewar** [comment]
I think the thing that's confusing me is that Arial isn't a fixed-width font.  If you do pick a fixed-width font (such as Courier), does the problem still happen?

(my worry is that something inside the code editor is assuming that the font being used is a fixed-width font, since that's what it's requesting, and that if the browser settings have been modified to use a non-fixed-width font when it's requested a fixed-width font, then that might be causing this weird cursor alignment problem you're seeing)

**Comment by tbekolay** [comment]
Also, can you go to the [ace.js homepage](https://ace.c9.io/#nav=about) and tell us if the issue exists there? We embed ace.js in `nengo_gui`, so it would be good to know if this is an issue with ace.js or how we embed ace.js.

**Comment by MichaelOVertolli** [comment]
That fixed it, but I actually had to change the type in both fixed width and sans-serif to Courier...

And, now I changed them back and everything is fine: no more displacement glitch.

No clue what is going on and the ace website seems fine to me.

Perhaps some kind of update issue? I haven't closed Chrome in a while.

**Comment by tcstewar** [comment]
Glad that did it....  Really not sure what the underlying problem was, though.  Perhaps the Chrome update/closing thing, but no real idea.

In any case, thanks for posting this issue, and if anyone else runs into this same problem hopefully the same fix will work...
