### ISSUE TITLE
Resizing the console messes up the GUI

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo-gui#689]
When resizing the console (by pulling it up), the simulation control disappears and the graph components  also get resized ([image](http://postimg.org/image/bltoliydp/)).  To reproduce: open the `default.py` example, add a print statement at the end of the script, this will do:

``` python
print a
```

Resize the console by pulling up. It seems to work fine when resizing the console by pulling the console down. 

"Bugfix": just click anywhere in the editor :)
Happens with: Chromium 48.0.2564.82 Built on 8.3, running on Debian 8.3

**Comment by jgosmann** [comment]
Hint: you can insert images directy into GitHub issues with drag&drop

Also, cannot reproduce this neither with Firefox 44.0.2 nor Chromium 48.0.2564.103 (64-bit), both on Chakra linux (rolling release). But I do get a slightly weird behaviour where the top border jumps up as soon as I start to drag and will be above the cursor. It will work correctly the second time I try to resize the console.

**Comment by krisfrenette** [comment]
As far as I can tell this is no longer happening.
