### ISSUE TITLE
For minimap

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#69]
- When does the area of concern grow?
- When does the AoC shrink?
- Does the Area of Concern follow the user's panning?

**Comment by cchan987** [comment]
Does the minimap include both netgraph and components or just the netgraph?

**Comment by tcstewar** [comment]
> Does the minimap include both netgraph and components or just the netgraph?

I think it should include both, but I'm not sure.

**Comment by tcstewar** [comment]
This exists now thanks to #242 and seems to have the right behaviour.
