### ISSUE TITLE
can't resize ensembles

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo-gui#703]
So on master of nengo_gui, when i start up nengo_gui I can't resize ensembles. When i got to the console it says 

``` bash
Uncaught TypeError: Cannot read property 'offsetX' of undefined : netgraph_item.js : 228
```

which is 

``` javascript
 var w = pos[0] - event.clientX + this.ng.offsetX;
```

when i log `this.ng` to the console it's null...

**Comment by studywolf** [comment]
seems to be fixed if you just drop the `this`

**Comment by studywolf** [comment]
looks like it was changed waaay back in 02583f420f21b1691233d0e5c4b2145e7e46d34e by @drasmuss , from `screen_offset`.

**Comment by tbekolay** [comment]
I think the proper fix would be `var self = this; ... self.ng.offsetX`.

But also, this is useful feedback in that since the sprint no one who's on master has tried to resize ensembles until now ;)

**Comment by studywolf** [comment]
yeah i was kind of shocked that no one has resized ensembles in the last
month and a half haha

**Comment by studywolf** [comment]
should all the other `ng. ...` references be changed to `self.ng` too?

**Comment by tbekolay** [comment]
Looks like there are a mix of `ng` and `self.ng` in there yeah... probably either is fine, but best to be consistent. I'd go with `self.ng`, but either way!

**Comment by studywolf** [comment]
alrighty, i'll update the PR
