### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#8]
- plots should be resizable from all edges
  - also resize on scrollwheel
  - also resize on pinch-zoom
- zoom the whole thing by scrollwheel or pinch-zoom on background

**Comment by celiasmith** [comment]
plots and sliders (all components) should be resizable from all edges, etc.

**Comment by cchan987** [comment]
cursor does not change when resizing plots

**Comment by tcstewar** [comment]
This all seems to be working now, other than the pinch-zoom, which should be a whole separate Issue involving touch screens in general.
