### ISSUE TITLE
Gui not working with Firefox on OS X

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-gui#852]
The editor doesn't really appear, though there is the divider at the right side (which cannot be dragged). There is a security error in the web console, but not sure if that's related.

<img width="1059" alt="ff" src="https://cloud.githubusercontent.com/assets/850157/22175483/672a4908-dfc3-11e6-96df-cd33e30ee581.png">

Chrome works btw.

**Comment by krisfrenette** [comment]
Tested and this is no longer an issue, so closing this out.
