### ISSUE TITLE
Speed throttle

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#91]
Have a way to set the desired speed

**Comment by Seanny123** [comment]
Where do you envision this fitting into the user interface? Click on speed to expose a context menu to adjust?

**Comment by tcstewar** [comment]
> Where do you envision this fitting into the user interface? Click on speed to expose a context menu to adjust?

I've been thinking about this a bit, and about various ways to implement it.  In Nengo 1.4, we did something pretty much like the context menu approach, with a few discrete options (fastest (no throttle), 1x, 0.1x, 0.01x, etc).  So that's sorta okay, but it always felt a bit weird to me.

So for this one, I've been kinda imagining an actual throttle.  That is, a slider where all the way to the right is full speed, and all the way to the left is stop, and in between is some monotonic delay system.  I'm just not sure whether it should be on a log-scale or linear.  :)  And the idea in my head is that slider is just always there, right underneath the speed measurement -- that way the slider itself doesn't need any numbers on it, as the speed measurement itself tells you how fast you're going.
