### ISSUE TITLE
Configure Settings not working in jupyter notebook

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo-gui#910]
Unable to configure settings when the gui is embedded in a jupyter notebook

Steps to reproduce:
create a nengo model
import the visualizer:  IPythonViz(model)
Click on Utilities -> Configure Settings

You will see that Configure options pane doesn't show up.

**Comment by Seanny123** [comment]
Resolved for me on the master branch, so I'm going to go ahead and close this issue.
