### ISSUE TITLE
Implement a statusbar for global tooltips

### ISSUE THREAD

**Issue by astoeckel** [nengo/nengo-gui#926]
Depending on the context (e.g. the mouse being over a certain element), the GUI may allow certain  modifier keys to change the behaviour of actions, such as mouse clicks/dragging (see #881). However, these modifiers are currently not discoverable by the user. To enhance discoverability, many applications such as MS Office, Gimp, or Inkscape possess a status bar (see [1] for evidence). 

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/bb760728(v=vs.85).aspx

**Comment by astoeckel** [comment]
I'm going to implement a prototype of this concept which works in conjunction with #881, so this feature can be evaluated.

**Comment by jgosmann** [comment]
This can be closed I assume?
