### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-gui#951]
Reasons:
* ~~Last release version won't start and fails with an exception (master works):~~ (edit: apparently I had some weird version installed, but the other points still stand)
```
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.6.1/bin/nengo", line 11, in <module>
    load_entry_point('nengo-gui==0.3.2.dev0', 'console_scripts', 'nengo')()
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo_gui/main.py", line 117, in main
    s.start()
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo_gui/gui.py", line 75, in start
    self.server.settings.prefix, self.server.auth_token))
TypeError: not all arguments converted during string formatting
```
* There are commits fixing security flaws: e68273bf5fcc1af7471b3e2d9738bf432ce16c9c, 9b515f8db3eb4f9cd64e91c2b875d1b122a1794e
* I wouldn't be opposed to have #920 and #923 merged before a release to mitigate further security concerns if this happens in a timely manner.

**Comment by Seanny123** [comment]
Should a release be done before the Summer School?

**Comment by jgosmann** [comment]
+1
Sent an email about this to @tcstewar and @Seanny123.

**Comment by jgosmann** [comment]
Two more PRs good to have:
#960 and #961

**Comment by tcstewar** [comment]
Release made!  I didn't get #921  in, or #959 and #860 .  

Thank you to everyone, and especially to @jgosmann, for all the many fixes and improvements in this release, and for continuing to bug me to get things merged. :)
