### ISSUE TITLE
Components should disappear behind the simcontrol

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#96]

**Comment by cchan987** [comment]
Note to self:
Change sim_control position to fixed and update its zindex with every time zindex increases for any component

**Comment by tcstewar** [comment]
> Change sim_control position to fixed and update its zindex with every time zindex increases for any component

Hmm...  that feels a bit ugly....   I'd also consider just setting its zindex to a very large value (that's what the popup config menu does)  https://github.com/nengo/nengo_viz/blob/master/nengo_viz/static/viz_menu.js#L41
