### ISSUE TITLE
Potential race condition in Jedi autocompletion?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-gui#975]
It seems that on some machines the autocompletion will break by typing too fast. There might be a race condition that another autocompletion request gets processed before the previous one finished which would give to concurrent jedi processes that might access the same cache.

**Comment by tcstewar** [comment]
This might possibly be related to #962 ?

**Comment by jgosmann** [comment]
Yes, I believe that is the same class of errors.
