### ISSUE TITLE
Don't allow nodes in the netgraph to overlap.

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#98]
Stop the dragging/zooming when two netgraph nodes collide

**Comment by tcstewar** [comment]
Do we have consensus on closing this?  Personally, I'm very happy with the current behaviour that's perfectly fine with letting things in the netgraph overlap.  But I'd thought people were still wanting to stop that behaviour somehow.

**Comment by celiasmith** [comment]
We can reopen if we want a memory of things that we considered on the road to the current look and feel.  I can see that being better for considering the most options, but worse for a messy repo :open_mouth:

**Comment by tcstewar** [comment]
I'm happy closing it if people agree.  I just didn't want to close it without hearing from others, as it's a pretty big decision.  That said, I'm strongly in favour of allowing the overlap.  People can do it if they want, and it simplifies moving things around in the network, and it simplifies code.  :)

**Comment by celiasmith** [comment]
Well, we have a consensus of two then :) ... But I'm happy to hear other opinions.

**Comment by jgosmann** [comment]
+1 allow overlap

**Comment by tbekolay** [comment]
I'm also +1 allowing overlap.

**Comment by tcstewar** [comment]
Cool!  That's close enough to consensus for me.  :)
