### ISSUE TITLE
No more SP cloud plots?

### ISSUE THREAD

**Issue by Kougakujin** [nengo/nengo-gui#984]
Hallo,
I've just downloaded the latest version of nengo_spa and when I'm clicking on e.g. transcode or state modules I no longer seem to have the option of seeing the SP cloud! All I can see is options for value, expand network and details. Any idea what might be causing this?
The problem seems to persist on older code where I could in the past most certainly obtain SP cloud plots.
Thanks.

**Comment by tcstewar** [comment]
Hello, you'll need the latest version of nengo_gui as well -- my guess is that the version you have doesn't know about `nengo_spa`, so it's not providing the plots!   

Let me know if that solves the problem!

**Comment by drasmuss** [comment]
You can get the latest version by doing `pip install nengo-gui --upgrade`

**Comment by tcstewar** [comment]
Note:  I'd recommend updating via `pip install nengo-gui --upgrade --no-deps`, as that will cause it to not try to upgrade other things on your computer (nengo and numpy).   `numpy` is the one that can sometimes cause problems when it upgrades, depending on your computer's configuration.

**Comment by drasmuss** [comment]
I figured it'd also be good to upgrade other things at the same time (like nengo), but yeah if you run into any problems `--no-deps` is a good thing to try :smile:

**Comment by krisfrenette** [comment]
This seems to be done so I am closing this out.
