### ISSUE TITLE
Investigate difficulty of putting everything on a canvas

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#99]

**Comment by tbekolay** [comment]
To add some more detail to this issue, the goal is to put all of the components in a single SVG node. Currently, each component is a div around an SVG node. Part of why this is done is to make it easier to use the [interact.js libarary](http://interactjs.io/), which is what we use to move and resize parts of the interface.

Interact.js advertises that it also works with SVG files; however, in the refactoring I experimented with this and found that it did not work as I expected. It appears to work when embedded within an SVG file, but it does not work in an HTML file that includes an SVG node. I'm not sure why; at the time I investigated it for a few hours, then gave up and used a div instead.

That doesn't mean that we can't put everything in the same SVG document though, it just means that we will still likely need to have some divs that are there for the sole purpose of working with interact.js. I'll address this while refactoring.
